# input
input_path: vcfinputs/

# output
output_path: bedinputs/
output_file: bedinputs/STEP0_ILL_Calls_all.bed 

#refs
reference: ./refs/GRCh38_full_analysis_set_plus_decoy_hla.fa
callers: ./refs/callers.txt 
contigs: ./refs/contig.txt 
blacklist: ./refs/human.hg38.excl.tsv 

